### ISSUE TITLE
History refactor

### ISSUE THREAD

**Issue by tmcclintock** [EbTech/AutoODE-DSL#8]
The `History` class could be a thin wrapper around a 3D Tensor that is shaped `(n_days, n_populations, n_regions)`. A `State` corresponds to an index in the i=1 dimension. This may be easier to work with.

**Comment by tmcclintock** [comment]
To elaborate - the constructor for a `History` should take in a `State` class. It should inspect the class to determine `n_populations` and `n_regions`. This way the `History` is abstracted away from SEITURD or SEIR or ...

**Comment by djsutherland** [comment]
Also option to parameterize `S = N - E - I - T - U - R - D`, etc.

**Comment by tmcclintock** [comment]
Closing since this was completed.
